version: '3.9'
services:
  node:
    container_name: thesis-data-collect-app
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:

 